[package]
name = "tch-backend-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmedge-sdk = { workspace = true }
tch = {workspace = true}
byteorder = "1.4.3"
anyhow = "1"
num-traits = "0.2"
num-derive = "0.3"
num = "0.4.0"
